### ISSUE TITLE
Helm-broker with helm3 + migration

### ISSUE THREAD

**Issue by PK85** [kyma-project/helm-broker#55]
**Description/Reasons**

As Helm 3 has been released it's time to investigate and update Helm Broker and take advantage of removed tiller and role-based access control per client.

**AC**
- [x] check and find out how to handle UI and kubectl access (idea: pass authenticated client/user from ServiceInstance custom resource  to helm install) - extracted to: https://github.com/kyma-project/helm-broker/issues/102
- [x] check, compare and document pros and cons of using:
  - pure helm3
  - flux - helm-operator
- [x] find out how migration will work
  - documentation proposal
  - take into account that tiller has others helm releases not from HB (should not be migrated)
  - small poc with migration
- [x] implement above investigation's results in the Helm Broker
- [ ] Update documentation - WIP (@piotrmiskiewicz)
- [ ] Decide if HB should be released or we should wait for impersonate user handling

**Attachments**

- check https://helm.sh/
- https://github.com/helm/helm-2to3
- check https://docs.fluxcd.io/projects/helm-operator/en/latest/

**Comment by mszostok** [comment]
consider going through the auth proxy instead of doing validation in Helm Broker

**Comment by mszostok** [comment]
check if user identity is sent in the request to the Helm Broker

**Comment by derberg** [comment]
Release still points to 1.9, please adjust
